data("iris")
install.packages("ggplot2")
library(ggplot2)
qplot(Petal.Length, Petal.Width, data = iris, color = Species)
install.packages("e1071")
mymodel<-e1071::svm(Species~., data = iris)
summary(mymodel)
plot(mymodel, data=iris, Petal.Width~Petal.Length, slice =list(Sepal.Width=3, Sepal.Length=4))
pred<-predict(mymodel,iris)